# Generated by Django 3.1.3 on 2020-11-25 01:07

import PyWEB_Exam2.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/images/default.jpg', storage=PyWEB_Exam2.storage_backend.PublicMediaStorage(), upload_to='profile_pics'),
        ),
    ]
