# Generated by Django 3.1.3 on 2020-11-25 02:08

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201125_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile/default.jpg', storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='profile_pics'),
        ),
    ]
