# Generated by Django 3.1.3 on 2020-12-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_clean_quote_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clean_quote_of_the_day',
            field=models.CharField(choices=[(True, 'No'), (False, 'Yes')], default=False, max_length=10),
        ),
    ]
