# Generated by Django 3.1.3 on 2020-12-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_blogposts_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blogposts_per_page',
            field=models.IntegerField(default=3),
        ),
    ]
