# Generated by Django 3.1.3 on 2020-11-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201128_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
