# Generated by Django 3.1.3 on 2020-11-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='state',
            field=models.CharField(choices=[('MAN', 'Mandatory'), ('OPT', 'Optional')], default=None, max_length=40),
        ),
    ]
