# Generated by Django 3.1.3 on 2020-11-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_entry_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='content',
            new_name='implementation',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='summary',
            new_name='requrement',
        ),
    ]
