# Generated by Django 3.1.3 on 2020-11-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201128_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='requrement',
            new_name='requirement',
        ),
    ]
