# Generated by Django 3.1.3 on 2020-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20201128_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.AlterField(
            model_name='entry',
            name='state',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Mandatory', 'Optional')], default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('To be implemented.', 'To be implemented'), ('Work in progress,', 'Work in progress'), ('Completed.', 'Completed and functional')], max_length=40),
        ),
    ]
