# Generated by Django 3.1.3 on 2020-12-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20201128_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_state', models.BooleanField(choices=[(True, 'Clean'), (False, 'Dirty')], default=True)),
                ('quote', models.CharField(max_length=140)),
            ],
        ),
    ]
