# Generated by Django 3.1.3 on 2020-12-07 21:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='implementation',
            field=ckeditor.fields.RichTextField(default=True),
            preserve_default=False,
        ),
    ]
